[build]
  command = "npm install && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "models/**", "routes/**", "service/**", "public/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  autoLaunch = false
