[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "models/**", "routes/**", "service/**", "public/**"]
  
[functions.server]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose", "ejs"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  autoLaunch = false
